### ISSUE TITLE
Tooltips massive after prepatch

### ISSUE THREAD

**Issue by Linnibin** [Itarater/XRP#8]
Hi there, 
I noticed that after the prepatch, the tooltips seem to display way more of the usually bloated 'currently' sections and therefore are absolutely massive.

If this is intended, could you create an option to shorten the currently section to only a few words/characters?

Thanks!
![wowscrnshot_072118_140845](https://user-images.githubusercontent.com/41512358/43035954-b2a4b636-8cef-11e8-93ea-5cc1c8bc2abd.jpg)

**Comment by Itarater** [comment]
What is being displayed there is fairly similar to how tooltips displayed before 8.0 in XRP. Did you attach the correct screenshot?

The tooltip currently is permitting three lines of text for lengthy fields rather than the former two, but I'm inclined to revert that change in the next release. However, that change would not impact what you've attached.

Specifically, are you referring to the number of lines, or to the overall width of the tooltip?

**Comment by Linnibin** [comment]
Hi,

to be fair, you might be correct... maybe I just never took notice of the actual width of the tooltip?

I personally would love an option to restrict the 'current' section to a couple of characters/words, though!

**Comment by Itarater** [comment]
If you are referring to the width, then it's possible it's a bit wider than before the patch. Maybe 20% wider? The method of measuring the width has changed, from characters (capping at ~60) to pixels (~500).

I've been planning to add an option to customize that width, I just haven't done it yet. It'll probably be coming in a fairly-near-future release.

**Comment by Linnibin** [comment]
That might just be it.

I noticed in MRP for example, there seems to be a character limit for the currently section; or it's pulling the format exactly form TRP including spacings and line breaks. I have attached screenshots.

If you could implement an option to customise the width, that would be great!

![wowscrnshot_072318_210227](https://user-images.githubusercontent.com/41512358/43100124-4650e7b0-8ebc-11e8-806d-53c66a01b6d2.jpg)
![wowscrnshot_072318_210249](https://user-images.githubusercontent.com/41512358/43100125-46715f36-8ebc-11e8-9a33-83b55fbcd241.jpg)

**Comment by Equimz** [comment]
Somewhat hijacking this, but it's related to tooltip size.
Any chance we could get something akin to the "Flag-style" from MRP? (Based on the old FlagRSP2 I guess).
By removing stuff like the "Currently" field and the "Character name" (Not IC name. But the thing that shows up in blue). To keep it far more compact. Might sound silly to some, but it's one of the main reasons why I can't switch over from MRP. Because.. I don't know, I don't like change or something!

**Comment by Itarater** [comment]
@Equimz Please file that as a new issue. If you could also attach a screenshot there as an example, it would be appreciated.

**Comment by Itarater** [comment]
@Linnibin There's a v2.0.0-beta2 release that includes the tooltip width and maximum line adjustments. If you want to test that, I'd appreciate it.

**Comment by Linnibin** [comment]
@Itarater I finally got around to testing the beta release. Thank you for this, I love the long-lines and tooltip functions, they really help with keeping the UI looking clean! Didn't run into any errors whatsoever. Appreciate it!

**Comment by Itarater** [comment]
Thanks for testing it. I'm closing this issue now, as this feature is now in a stable release (v2.0.0). If you run into any more issues, please feel free to file a new issue.
